[project]
name = "src"
version = "0.0.1"
description = "An MLOps project for predictive maintenance"
authors = [{name = "Md Arsalan Arshad", email = "arsalankhanrkl@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}